import { z } from 'zod/v4';

export const STORE_PERMISSIONS = [
	'store.read',
	'store.write',
	'store.delete',
	'products.create',
	'products.read',
	'products.update',
	'products.delete',
	'categories.create',
	'categories.read',
	'categories.update',
	'categories.delete',
	'orders.read',
	'orders.update',
	'orders.cancel',
	'orders.refund',
	'returns.read',
	'returns.update',
	'customers.read',
	'customers.update',
	'support_tickets.read',
	'support_tickets.update',
	'support_tickets.assign',
	'warehouse.read',
	'warehouse.update',
	'inventory.read',
	'inventory.manage_stock',
	'suppliers.read',
	'suppliers.update',
	'purchase_orders.read',
	'purchase_orders.approve',
	'promotions.create',
	'promotions.read',
	'promotions.update',
	'promotions.activate',
	'messages.read',
	'messages.send',
	'staff.create',
	'staff.read',
	'staff.update',
	'roles.create',
	'roles.read',
	'roles.update',
	'roles.delete',
	'reports.read',
	'reports.export',
] as const;

export const permissionSchema = z.enum(STORE_PERMISSIONS);
export type PermissionKey = z.infer<typeof permissionSchema>;
export const Permission = permissionSchema.enum;
